name: Release Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: Jmainguy/docker-workflows/.github/workflows/docker-release.yml@v4.0.1
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      notation_private_key: ${{ secrets.NOTATION_PRIVATE_KEY }}
      notation_certificate_chain: ${{ secrets.NOTATION_CERTIFICATE_CHAIN }}
      notation_ca_certificate: ${{ secrets.NOTATION_CA_CERTIFICATE }}
    with:
      docker_url: zot.soh.re
      registry_namespace: jmainguy
      image_name: ${{ github.event.repository.name }}
      authors: "Jonathan Seth Mainguy <jon@soh.re>"
      vendor: "Jmainguy"
      url: "https://github.com/${{ github.repository }}"
      source: "https://github.com/${{ github.repository }}"
      description: "A Docker image for statuscode"
      title: "Statuscode Docker Image"
      licenses: "GPL-2.0-only"
